# Generated by Django 5.2.6 on 2025-10-09 13:00

import ConferenceApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='payed',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=30, message='La description doit contenir au minimum 30 caractères')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='keywords',
            field=models.TextField(validators=[ConferenceApp.models.validate_keywords]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(upload_to='papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
